### ISSUE TITLE
Both Nginx and Apache access forbidden

### ISSUE THREAD

**Issue by Scapal** [sapk/docker-volume-rclone#16]
I'm using your driver with Docker in swarm mode.

When using Nginx or Apache I'm unable to access the files mounted with the volume using your driver.
If I exec a bash inside an instantiated container, I can see and read the mounted content.
Apache gives me a more detailed error: "access denied because search permissions are missing on a component of the path".

I checked the permissions on the mounted folder and accessed file: 

```
drwxr-xr-x  1 root root    0 Jun 17 17:32 uploads
-rw-r--r--  1 root root  129 Jul 24  2015 test.txt
```

The only strange thing I see, is that there are no `.` and `..` directory entries when I `ls -a` from inside the 'uploads' directory or any sub directories.

**Comment by sapk** [comment]
I would need more information on what type of backend you use to be able to reproduce.
You can also try to play with the args option to use rclone flags (https://rclone.org/commands/rclone_mount/) to adjust perms and maybe try to disable (for testing) selinux. You can check selinux config with `sestatus`

**Comment by Scapal** [comment]
Nevermind, it was the --allow-other .
I added it afterward but it seems I forgot to remove the existing volume without the option first.
