### ISSUE TITLE
Add rclone cache support

### ISSUE THREAD

**Issue by Wundark** [sapk/docker-volume-rclone#18]
I have been using this for the past day and this volume plugin has worked flawlessly. Thanks

In rclone you can specify a [cache](https://rclone.org/cache/) to preserve network io and costs associated with accessing similar files many times.

Would it be possible to have the ability to provide a volume to this volume plugin to use a caching directory on the host?

**Comment by sapk** [comment]
Yes it works and that what I am using.
Just generate a working rclone config file and base64 it.
If you want I should be able to provide you my configuration as an example.

**Comment by Wundark** [comment]
If you could provide your config that would be great. On my side I can't see any data being written to the cache folder.

**Comment by sapk** [comment]
If you installed the "managed" plugin version (docker plugin install command) the plugin is running inside a "hidden" container managed by docker. The cache folder would be inside this container and not the host path.

You can round more details on another plugin of mine : https://github.com/sapk/docker-volume-gluster#legacy-plugin-installation 
Or
https://github.com/sapk/docker-volume-rclone#how-to-debug-docker-managed-plugin-

**Comment by sapk** [comment]
For the configuration, you can find an example here : https://github.com/sapk/docker-volume-rclone/issues/9#issuecomment-457955774

**Comment by sapk** [comment]
In last [release](https://github.com/sapk/docker-volume-rclone/releases/tag/v0.0.6), I added a variant `-with-mount` that define a mountpoint on host that could be changed (https://docs.docker.com/engine/reference/commandline/plugin_set/#change-the-source-of-a-mount) to be use mainly to keep cached file outside container but I need to play with it before to choose the best solution. But feel free to try it if you want.
