### ISSUE TITLE
RFE: Support additional Docker Volume options

### ISSUE THREAD

**Issue by iFloris** [sapk/docker-volume-rclone#43]
- Plugin version (or commit ref) : sapk/plugin-rclone:latest
- Docker version : 19.03.13
- Plugin type : managed
- Operating system: Ubuntu Server 20.02

## Description
I am trying to use docker-volume-rclone as an alternative to RexRay/S3FS.
It almost works, but there are a few things missing:
- Ability to specify GID, UID and umask. This gets accepted with using --opt but it does not seem to actually use the option.
- Ability to specify rclone options such as `allow-non-empty` and `allow-other`. As before, the --opt gets accepted, but does not seem to do anything.
- Ability to use plugin in `Scope: Global` for use with Docker in Swarm mode. Right now, the volume is local, which stops a container from moving between Docker hosts.

## Logs

Test command:
```
docker volume create --driver sapk/plugin-rclone \
--opt config="$(base64 ~/.config/rclone/rclone.conf)" \
--opt remote=wasabi-s3:captain--test-s3 \
--opt uid=1001 \
--opt gid=root \
--opt umask=0022 \
--opt allow_other \
--opt use_path_request_style \
--opt allow_non_empty \
--name captain--test-s3
```
Docker volume inspect result:
```
[
    {
        "CreatedAt": "2020-11-10T11:00:05Z",
        "Driver": "sapk/plugin-rclone:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker-volumes/rclone/captain--test-s3",
        "Name": "captain--test-s3",
        "Options": {
            "allow_non_empty": "",
            "allow_other": "",
            "config": "[edited out]",
            "gid": "root",
            "remote": "wasabi-s3:captain--test-s3",
            "uid": "1001",
            "umask": "0022",
            "use_path_request_style": ""
        },
        "Scope": "local"
    }
]
```

This in comparison to RexRay/S3FS Docker volume inspect result:
```
[
    {
        "CreatedAt": "0001-01-01T00:00:00Z",
        "Driver": "rexray/s3fs:latest",
        "Labels": null,
        "Mountpoint": "",
        "Name": "captain--test2-s3",
        "Options": null,
        "Scope": "global",
        "Status": {
            "availabilityZone": "",
            "fields": null,
            "iops": 0,
            "name": "captain--test2-s3",
            "server": "s3fs",
            "service": "s3fs",
            "size": 0,
            "type": ""
        }
    }
]
```

The GID and GUID of the docker-volume-rclone volume remains at root:root. I tried to inspect and chown the volume test contents with an intermediate container. This is probably due to fuse, so I should set the GID, GUID and umask at the point of volume creation.
```
docker run -v captain--test-s3:/mnt/s3-endpoint -it --rm --name ubuntu-permissions-fixer ubuntu /bin/bash
root@45395027f995:/# ls -lah /mnt/s3-endpoint/
total 0
drwxr-xr-x 1 root root 0 Nov 10 11:22 data
root@45395027f995:/# chown 1001:root -Rv /mnt/s3-endpoint/*
changed ownership of '/mnt/s3-endpoint/data' from root:root to 1001:root
root@45395027f995:/# ls -lah /mnt/s3-endpoint/
total 0
drwxr-xr-x 1 root root 0 Nov 10 11:22 data
```

**Comment by DBWebdiensten** [comment]
I'm working alongside @iFloris on this and the docker-compose example and looking into the code after https://github.com/sapk/docker-volume-rclone/blob/master/rclone/driver/driver.go#L285 show'd that it was possible to use `--opt args="parameters"`.

We we came to the following result:
```
docker volume create --driver sapk/plugin-rclone --opt config="$(base64 ~/.config/rclone/rclone.conf)" --opt args="--uid 33 --gid 33" --opt remote=wasabi-s3:captain--fileuploadtestdynamic/data --name captain--fileuploadtestdynamic
```

Which seems to work partly, as going into the container `docker exec -i -t container-name /bin/bash` the volume is mounted to shows the mount point `/var/www/html/uploads` and the test files at our S3 storage:

```
root@e3d98284156d:/var/www/html# ls -lhtrR
.:
total 20K
-rw-r--r-- 1 www-data www-data 4.6K Oct 28 14:02 index.php
drwxr-xr-x 1 www-data www-data    0 Nov 11 13:36 uploads
-rw-r--r-- 1 www-data www-data  574 Nov 11 13:47 Dockerfile

./uploads:
total 0
-rw-r--r-- 1 www-data www-data 0 Nov 11 12:09 File.txt
-rw-r--r-- 1 www-data www-data 0 Nov 11 12:14 File2.txt
-rw-r--r-- 1 www-data www-data 0 Nov 11 13:02 File3.txt
-rw-r--r-- 1 www-data www-data 0 Nov 11 13:49 File4.txt
-rw-r--r-- 1 www-data www-data 0 Nov 11 13:52 FileTwake.txt
```

We're also able to read & write files through `docker exec -i -t container-name /bin/bash` but unfortunately, Apache itself even though UID & GID and chmod rights are correct, can't see or use the mount point:

- https://s3.eu-central-1.wasabisys.com/public-random/File-Upload-Test-Dynamic.png
- https://s3.eu-central-1.wasabisys.com/public-random/index.php

The `--allow-non-empty`, `--allow-root` and `--allow-other` commands don't seem to pass along and play nice in the `--opt args="parameters"` area as the mount isn't available when these are added.

So we're probably overlooking something at this stage, any direction(s) or help would be much appreciated.
My guess is that it is something with rights in combination with how rclone has mounted the files in the volume trough the plugin.

**Comment by sapk** [comment]
Thanks for the details reports. 
I think I narrowed the args problem that doesn't allow multiples args to be passed (the params are escaped with ").
I will test this and fix it.

For the scope Global, It can only be achieve with a controller architecture that will controller all the nodes .
In the meantime, the plugin is already compatible with swarm, you just need to install it on every nodes before and the volume will be available.

**Comment by iFloris** [comment]
Thanks a lot @sapk for your efforts. We appreciate any and all help 😄

**Comment by sapk** [comment]
Running exec with -u flag (`docker exec -i -t -u 33:33 ubuntu /bin/ls -lah /mnt`) to set user I get `/bin/ls: cannot access '/mnt': Permission denied` which seems to be a way to reproduce the bug with a local mountpoint. 
But using the flags `--allow-other --allow-root` seems to works as attended.

For details, that the commands I executed (the base64 for config expose a remote (local) at local-test:):
```bash
docker volume create --driver sapk/plugin-rclone --opt config="W2xvY2FsLXRlc3RdCnR5cGUgPSBsb2NhbAoK" --opt args="--uid 33 --gid 33" --opt remote=local-test:/ --name test
docker run -i -t -u 33:33 --rm -v test:/mnt ubuntu /bin/ls -lah /mnt
# result similar to you : /bin/ls: cannot access '/mnt': Permission denied

# (clean with docker volume rm test)
docker volume create --driver sapk/plugin-rclone --opt config="W2xvY2FsLXRlc3RdCnR5cGUgPSBsb2NhbAoK" --opt args="--uid 33 --gid 33 --allow-root --allow-other" --opt remote=local-test:/ --name test
docker run -i -t -u 33:33 --rm -v test:/mnt ubuntu /bin/ls -lah /mnt
# I get the content of the plugin root and can also read content of files.
```

**Comment by DBWebdiensten** [comment]
Thank you @sapk for you're examples, we use [CapRover](https://caprover.com), which does most of the work for us as a PaaS solution.

Specif icing `-u 33:33` in the docker run command isn't something CapRover does and after testing without it, it works by 'simply' changing the 'args' from:

```
--opt args="--uid 33 --gid 33"
```

To:

```
--opt args="--uid 33 --gid 33 --allow-root --allow-other"
```

From the top of my mind, I've tested with both parameters `--allow-root` and `--allow-other` separately which didn't work, but not combined, which does just the trick.

So as it works now as shown [here](https://s3.eu-central-1.wasabisys.com/public-random/screenshot-full-page.jpg), that is great.

You're help is much appreciated!

**Comment by sapk** [comment]
To be honest I don't exactly know why we need both parameters --allow-root and --allow-other but it should be related to rclone/fuse.

The -u was just to simulate on ubuntu image the user change (USER in the dockerfile) that must occur in the docker image that you use. You shouldn't need it in prod.
