### ISSUE TITLE
How to remove a volume created by rclone?

### ISSUE THREAD

**Issue by everyx** [sapk/docker-volume-rclone#49]
- Plugin version (or commit ref) : latest
- Docker version : 20.10.1
- Plugin type : managed
- Operating system: Ubuntu 20.04.1 LTS

## Description

I can't remove volume, even if I use `-f` option, are there any other ways we can workaround it?

## Logs

```shell
~ docker volume rm -f bitwarden_bitwarden-data
Error response from daemon: remove bitwarden_bitwarden-data: VolumeDriver.Remove: remove /var/lib/docker-volumes/rclone/bitwarden_bitwarden-data: directory not empty
```

**Comment by sapk** [comment]
Hello
It seems strange that the unmount didn't work but if you haven't any other volume running you can force disable/remove the plugin globally. 
Docker doesn't advertise the plugin that the flag used so I can not force removal on plugin side.

**Comment by everyx** [comment]
> Hello
> It seems strange that the unmount didn't work but if you haven't any other volume running you can force disable/remove the plugin globally.
> Docker doesn't advertise the plugin that the flag used so I can not force removal on plugin side.

When I mount this volume and remove all files in the container which mounted it, I can remove it by `docker volume rm -f bitwarden_bitwarden-data`
